logger:
  version: 1
  disable_existing_loggers: false
  formatters:
    simple:
      format: >-
          %(asctime)s [%(process)s] [%(processName)s] [%(threadName)s]
          %(levelname)s %(name)s:%(lineno)d - %(message)s
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    console:
      class: rich.logging.RichHandler
      formatter: simple
  loggers:
    adal-python:
      level: WARNING
  root:
    level: INFO
    handlers:
      - console